version: '3'

services:
  auto-repository:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnectionString=Host=repository.sql.data;Port=5432;Database=auto-db;Username=postgres;Password=postgres
    ports:
      - "8888:80"


  repository.sql.data:
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5433:5432"