version: '3'

services:
  repository.sql.data:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  redis.cache:
    image: redis
    ports:
      - "6379:6379"