version: '3'

services:

  auto-repository:
    image: auto/repository
    build:
      context: ./auto-repository/src/AutoRepository
      dockerfile: Dockerfile
    depends_on:
      - repository.sql.data


  repository.sql.data:
    image: postgres

  redis.cache:
    image: redis
    ports:
      - "6379:6379"