apiVersion: v1
kind: ConfigMap
metadata:
  name: externalcfg
  namespace: auto
  labels:
    app: automobile
data:
  AutoSqlDb: Host=sql-data;Port=5432;Database=auto-db;Username=postgres;Password=postgres
  RedisCache: redis-cache
---
apiVersion: v1
kind: Service
metadata:
  name: sql-data
  namespace: auto
  labels:
    app: automobile
    component: sql-data
spec:
  type: NodePort
  ports:
  - port: 5432
  selector:
    app: automobile
    component: sql-data
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sql-data
  namespace: auto 
spec:
  template:
    metadata:
      labels:
        app: automobile
        component: sql-data
    spec:
      containers:
      - name: sql-data
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache
  namespace: auto
  labels:
    app: automobile
    component: redis-cache
spec:
  ports:
  - port: 6379
  selector:
    app: automobile
    component: redis-cache
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-cache
  namespace: auto
spec:
  template:
    metadata:
      labels:
        app: automobile
        component: redis-cache
    spec:
      containers:
      - name: redis-cache
        image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: auto-repository
  namespace: auto
  labels:
    app: automobile
    component: auto-repository
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: automobile
    component: auto-repository
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auto-repository
  namespace: auto
spec:
  template:
    metadata:
      labels:
        app: automobile
        component: auto-repository
    spec:
      containers:
      - name: auto-repository
        image: localhost:5000/automobile
        env:
        - name: DbConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: AutoSqlDb
        - name: RedisConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: RedisCache
---